#ACUMOS Apache-2.0
#Software in this Acumos repository is distributed by the authors
#under the Apache License, Version 2.0 (the "License").
 
#This Acumos software repository includes files that are Copyright
#2014-2017 Hippo B.V. (http://www.onehippo.com) and distributed under the
#Apache License, Version 2.0 (the "License").
 
#You may not use this file except in compliance with the License.
#You may obtain a copy of the License at
 
  #   http://www.apache.org/licenses/LICENSE-2.0
 
#This software is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
 
#ACUMOS CC-BY-4.0
#Documentation in this repository is distributed by the authors
#under the Creative Commons Attribution 4.0 International License (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
 
#http://creativecommons.org/licenses/by/4.0
 
#This documentation is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.



definitions:
  namespace:
    acumoscms:
      uri: http://www.onehippo.org/acumoscms/nt/1.0
      cnd: namespaces/acumos-cms.cnd
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
    /hippo:configuration/hippo:groups/author:
      hipposys:members:
        operation: add
        type: string
        value: [author]
    /hippo:configuration/hippo:groups/editor:
      hipposys:members:
        operation: add
        type: string
        value: [editor]
    /hippo:configuration/hippo:groups/webmaster:
      hipposys:members:
        operation: add
        type: string
        value: [editor]
    /hippo:configuration/hippo:domains/hippofolders/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [sitewriters]
    /hippo:configuration/hippo:domains/preview-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [previewusers]
    /hippo:configuration/hippo:domains/live-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [liveusers]
